site_name: Arduino Docs
site_url: https://example.com/
site_description: Arduino Doc.
site_author: Paramesh Chandra.

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists

plugins:
    - search

nav:
    - 'Home': 'index.md'
    - 'Chapter 1':
        - 'Arduino-Overview': '1.Chapter-1\1.Arduino-Overview.md'
        - 'Arduino-Board-Description': '1.Chapter-1\2.Arduino-Board-Description.md'
        - 'Installation': '1.Chapter-1\3.Installation.md'
        - 'Tinkar Simulation': '1.Chapter-1\3.Tinkar Simulation.md'
    - 'Chapter 2':
        - 'Program Structure': '2.Chapter-2\1.Program Structure.md'
        - 'Data Types': '2.Chapter-2\2.Data Types.md'
        - 'Variables and Constants': '2.Chapter-2\3.Variables and Constants.md'
        - 'Operators': '2.Chapter-2\4.Operators.md'
        - 'Control Statements': '2.Chapter-2\5.Control Statements.md'
        - 'Loops': '2.Chapter-2\6.Loops.md'
        - 'Functions': '2.Chapter-2\7.Functions.md'
        - 'Time': '2.Chapter-2\8.Time.md'
    - 'Arduino Projects':
        - 'Blinking LED': '3.Arduino Projects\1.Blinking LED.md'
        - 'Fading LED': '3.Arduino Projects\2.Fading LED.md'
        - 'Reading Analog Voltage': '3.Arduino Projects\3.Reading Analog Voltage.md'
        - 'Temperature Sensor': '3.Arduino Projects\4.Temperature Sensor.md'
        - 'RC circuit data log': '3.Arduino Projects\5.RC circuit data log.md'
        - 'Reading Analog Voltage More than 5V': '3.Arduino Projects\6.Reading Analog Voltage More than 5V.md'
        - '7 Segment Display': '3.Arduino Projects\7.7 Segment Display.md'
        - 'Ultrasonic Sensor': '3.Arduino Projects\8.Ultrasonic Sensor.md'
        - 'LCD Display': '3.Arduino Projects\9.LCD Display.md'
#repo_url: https://github.com/paramphy/Arduino-doc/
#edit_uri: ""

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - attr_list
    - def_list
    - mdx_math
      #enable_dollar_delimiter: True

copyright: Maintained by the <a href="https://github.com/paramphy">Paramesh Chandra</a>.

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

    
    