site_name: Arduino Docs
site_url: https://example.com/

#plugins:
#    - with-pdf
nav:
    - 'index.md'
    - Chapter 1:
      - 'Chapter-1\Arduino-Overview.md'
      - 'Chapter-1\Arduino-Board-Description.md'
      - 'Chapter-1\Installation.md'
    - Chapter 2:
      - 'Chapter-2\Program Structure.md'
      - 'Chapter-2\Data Types.md'
      - 'Chapter-2\Variables and Constants.md'
      - 'Chapter-2\Operators.md'
      - 'Chapter-2\Control Statements.md'
      - 'Chapter-2\Loops.md'
      - 'Chapter-2\Functions.md'
      - 'Chapter-2\Time.md'
    - Arduino Projects:
      - 'Arduino Projects\Blinking LED.md'
      - 'Arduino Projects\Fading LED.md'
      - 'Arduino Projects\Reading Analog Voltage.md'
      - 'Arduino Projects\Temperature Sensor.md'

#repo_url: https://github.com/paramphy/Arduino-doc.git