site_name: Arduino Docs
site_url: https://example.com/
site_description: Arduino Doc.
site_author: Paramesh Chandra.

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists

plugins:
    - search
    #- mkpdfs
    - print-site

#nav:
#    - 'index.md'
#    - Chapter 1:
#      - Arduino-Overview: 'Chapter-1\Arduino-Overview.md'
#      - Arduino-Board-Description: 'Chapter-1\Arduino-Board-Description.md'
#      - Installation: 'Chapter-1\Installation.md'
#    - Chapter 2:
#      - 'Chapter-2\Program Structure.md'
#      - 'Chapter-2\Data Types.md'
#      - 'Chapter-2\Variables and Constants.md'
#      - 'Chapter-2\Operators.md'
#      - 'Chapter-2\Control Statements.md'
#      - 'Chapter-2\Loops.md'
#      - 'Chapter-2\Functions.md'
#      - 'Chapter-2\Time.md'
#    - Arduino Projects:
#      - 'Arduino Projects\Blinking LED.md'
#      - 'Arduino Projects\Fading LED.md'
#      - 'Arduino Projects\Reading Analog Voltage.md'
#      - 'Arduino Projects\Temperature Sensor.md'

#repo_url: https://github.com/paramphy/Arduino-doc/
#edit_uri: ""

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - attr_list
    - def_list
    - mdx_math
      #enable_dollar_delimiter: True

copyright: Maintained by the <a href="https://github.com/paramphy">Paramesh Chandra</a>.

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

    
    